[package]
name = "gcsf"
description = "Filesystem based on Google Drive"
version = "0.2.0"
repository = "https://github.com/harababurel/gcsf"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"
keywords = ["google", "drive", "fuse", "filesystem"]
exclude = ["build/**/*.o", "doc/**/*.html", "client_secret.json", "/ci/*"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = { version = "2.33", features = ["yaml"] }
config = "0.11"
ctrlc = { version = "3.1", features = ["termination"] }
failure = "0.1"
fuser = { version = "0.7", features = ["abi-7-11"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
google-drive3 = "2.0.2"
id_tree = "1.7"
itertools = "0.10"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
lru_time_cache = "0.11"
maplit = "1.0"
mime-sniffer = "0.1"
pretty_env_logger = "0.4"
rand = "0.8"
rust-embed = { version= "5.8", features = ["debug-embed"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
xdg = "2.2"

# google-drive3 intentionally uses an old version of hyper. See
# https://github.com/Byron/google-apis-rs/issues/173 for more
# information.
hyper = "^0.14"
hyper-rustls = { version = "^0.22", features = ["rustls-native-certs", "webpki-roots"]}
yup-oauth2 = "^5.0"

[profile.release]
debug = true
